version: '3'

services:
  portainer:
    image: portainer/portainer
    command: 
      --no-auth
      -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  visualizer:
    image: alexellis2/visualizer-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:8080
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  portainer_data:
    driver: local