version: '3'

services:
  influx:
    image: jsdidierlaurent/rpi-influxdb
    volumes:
      - influx-db:/var/lib/influxdb
      - influx-cgroup:/sys/fs/cgroup
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: jsdidierlaurent/rpi-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana
      - grafana-cgroup:/sys/fs/cgroup
    depends_on:
      - influx
    deploy:
      placement:
        constraints:
          - node.role == manager

  cadvisor-rpi:
    image: niplodim/cadvisor-rpi
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == arm

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - influx
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == amd

volumes:
  influx-db:
    driver: local
  influx-cgroup:
    driver: local
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
  grafana-cgroup:
    driver: local